[package]
name = "templateTest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed = "*"
serde = {version = "*", features = ["derive"]}
tera = "*"
serde_yaml = "*"