[package]
name = "test-env"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-nats = "0.29.0"
bytes = "1.4.0"
futures = "0.3.28"
nats = "0.24.0"
tokio = {version = "1.28.1", features=["full"] }
